
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Label label1;
	private global::Gtk.ComboBox cmbEstado;
	private global::Gtk.Label label2;
	private global::Gtk.CheckButton chkAleman;
	private global::Gtk.CheckButton chkIngles;
	private global::Gtk.CheckButton chkIslandes;
	private global::Gtk.RadioButton radMasculino;
	private global::Gtk.RadioButton radFemenino;
	private global::Gtk.Label label3;
	private global::Gtk.Label label4;
	private global::Gtk.Calendar calFecha;
	private global::Gtk.Label label5;
	private global::Gtk.SpinButton spinEdad;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TextView txtComentarios;
	private global::Gtk.Label label6;
	private global::Gtk.Button btnGuardar;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Estado");
		this.fixed1.Add (this.label1);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label1]));
		w1.X = 12;
		w1.Y = 12;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.cmbEstado = global::Gtk.ComboBox.NewText ();
		this.cmbEstado.AppendText ("");
		this.cmbEstado.AppendText (global::Mono.Unix.Catalog.GetString ("Jalisco"));
		this.cmbEstado.AppendText (global::Mono.Unix.Catalog.GetString ("Nayarit"));
		this.cmbEstado.AppendText (global::Mono.Unix.Catalog.GetString ("Colima"));
		this.cmbEstado.AppendText (global::Mono.Unix.Catalog.GetString ("Yucatan"));
		this.cmbEstado.Name = "cmbEstado";
		this.fixed1.Add (this.cmbEstado);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.cmbEstado]));
		w2.X = 20;
		w2.Y = 40;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Idiomas");
		this.fixed1.Add (this.label2);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label2]));
		w3.X = 19;
		w3.Y = 88;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.chkAleman = new global::Gtk.CheckButton ();
		this.chkAleman.CanFocus = true;
		this.chkAleman.Name = "chkAleman";
		this.chkAleman.Label = global::Mono.Unix.Catalog.GetString ("Aleman");
		this.chkAleman.DrawIndicator = true;
		this.chkAleman.UseUnderline = true;
		this.fixed1.Add (this.chkAleman);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.chkAleman]));
		w4.X = 15;
		w4.Y = 112;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.chkIngles = new global::Gtk.CheckButton ();
		this.chkIngles.CanFocus = true;
		this.chkIngles.Name = "chkIngles";
		this.chkIngles.Label = global::Mono.Unix.Catalog.GetString ("Inglés");
		this.chkIngles.DrawIndicator = true;
		this.chkIngles.UseUnderline = true;
		this.fixed1.Add (this.chkIngles);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.chkIngles]));
		w5.X = 15;
		w5.Y = 135;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.chkIslandes = new global::Gtk.CheckButton ();
		this.chkIslandes.CanFocus = true;
		this.chkIslandes.Name = "chkIslandes";
		this.chkIslandes.Label = global::Mono.Unix.Catalog.GetString ("Islandes");
		this.chkIslandes.DrawIndicator = true;
		this.chkIslandes.UseUnderline = true;
		this.fixed1.Add (this.chkIslandes);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.chkIslandes]));
		w6.X = 17;
		w6.Y = 160;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.radMasculino = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Masculino"));
		this.radMasculino.CanFocus = true;
		this.radMasculino.Name = "radMasculino";
		this.radMasculino.DrawIndicator = true;
		this.radMasculino.UseUnderline = true;
		this.radMasculino.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this.fixed1.Add (this.radMasculino);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.radMasculino]));
		w7.X = 18;
		w7.Y = 238;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.radFemenino = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Femenino"));
		this.radFemenino.CanFocus = true;
		this.radFemenino.Name = "radFemenino";
		this.radFemenino.DrawIndicator = true;
		this.radFemenino.UseUnderline = true;
		this.radFemenino.Group = this.radMasculino.Group;
		this.fixed1.Add (this.radFemenino);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.radFemenino]));
		w8.X = 18;
		w8.Y = 265;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Sexo");
		this.fixed1.Add (this.label3);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label3]));
		w9.X = 20;
		w9.Y = 200;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Fecha de nacimiento");
		this.fixed1.Add (this.label4);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label4]));
		w10.X = 202;
		w10.Y = 30;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.calFecha = new global::Gtk.Calendar ();
		this.calFecha.CanFocus = true;
		this.calFecha.Name = "calFecha";
		this.calFecha.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
		this.fixed1.Add (this.calFecha);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.calFecha]));
		w11.X = 212;
		w11.Y = 73;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Edad");
		this.fixed1.Add (this.label5);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label5]));
		w12.X = 22;
		w12.Y = 297;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spinEdad = new global::Gtk.SpinButton (10, 40, 1);
		this.spinEdad.CanFocus = true;
		this.spinEdad.Name = "spinEdad";
		this.spinEdad.Adjustment.PageIncrement = 10;
		this.spinEdad.ClimbRate = 1;
		this.spinEdad.Numeric = true;
		this.spinEdad.Value = 10;
		this.fixed1.Add (this.spinEdad);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.spinEdad]));
		w13.X = 22;
		w13.Y = 315;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.txtComentarios = new global::Gtk.TextView ();
		this.txtComentarios.WidthRequest = 440;
		this.txtComentarios.HeightRequest = 158;
		this.txtComentarios.CanFocus = true;
		this.txtComentarios.Name = "txtComentarios";
		this.GtkScrolledWindow.Add (this.txtComentarios);
		this.fixed1.Add (this.GtkScrolledWindow);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.GtkScrolledWindow]));
		w15.X = 26;
		w15.Y = 370;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Observaciones");
		this.fixed1.Add (this.label6);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label6]));
		w16.X = 30;
		w16.Y = 347;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnGuardar = new global::Gtk.Button ();
		this.btnGuardar.CanFocus = true;
		this.btnGuardar.Name = "btnGuardar";
		this.btnGuardar.UseUnderline = true;
		this.btnGuardar.Label = global::Mono.Unix.Catalog.GetString ("Guardar");
		this.fixed1.Add (this.btnGuardar);
		global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnGuardar]));
		w17.X = 404;
		w17.Y = 284;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 601;
		this.DefaultHeight = 547;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.Shown += new global::System.EventHandler (this.OnShown);
		this.cmbEstado.Changed += new global::System.EventHandler (this.OnCombobox1Changed);
		this.calFecha.PrevMonth += new global::System.EventHandler (this.OnCalFechaPrevMonth);
		this.calFecha.NextMonth += new global::System.EventHandler (this.OnCalFechaNextMonth);
		this.calFecha.DaySelected += new global::System.EventHandler (this.OnCalFechaDaySelected);
		this.btnGuardar.Clicked += new global::System.EventHandler (this.OnBtnGuardarClicked);
	}
}
